server:
  port: 8090  # Cambiado de 8080 a 8090

spring:
  datasource:
    url: jdbc:mysql://mysql8:3306/manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: SUPERCLAVE
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#
