server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql8:3306/manager?useSSL=false&serverTimezone=UTC
    username: ${_USER_MYSQL}
    password: ${_PASSWORD_MYSQL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
