name: Deploy Cliente to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Debug: verificar que los secrets están definidos
      - name: Check secrets
        run: |
          echo "HOST_VPS=${{ secrets.HOST_VPS }}"
          echo "USERNAME_VPS=${{ secrets.USERNAME_VPS }}"
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "SSH_KEY is empty!"
            exit 1
          else
            echo "SSH_KEY is set ✅"
          fi

      # 3️⃣ Copiar archivos al VPS (nueva ruta y usuario devops)
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_VPS }}
          username: ${{ secrets.USERNAME_VPS }} # debe ser devops en los secrets
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/Cliente-app"

      # 4️⃣ Ejecutar comandos de deploy en VPS (nueva ruta y permisos)
      - name: Run deploy commands on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_VPS }}
          username: ${{ secrets.USERNAME_VPS }} # debe ser devops
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Verificando que estamos en el VPS correcto..."
            whoami
            pwd

            # Navegar a la carpeta del proyecto
            cd /var/www/Cliente-app
            
            # Construir la nueva imagen de Docker
            docker build -t cliente_image .

            # Detener y eliminar el contenedor existente si está corriendo
            docker stop cliente_container || true
            docker rm cliente_container || true

            # Ejecutar el nuevo contenedor con la nueva imagen
            docker run -d \
              --name cliente_container \
              -p 8090:8090 \
              --memory="512m" \
              --memory-reservation="512m" \
              --cpus="0.5" \
              cliente_image






